table IndexPrices
	lineageTag: 7450b6d1-8096-46dc-a768-51eafcb3f32b

	column Symbol
		dataType: string
		lineageTag: be587f76-b2e1-4632-84ca-d77ae2ca6bbd
		summarizeBy: none
		sourceColumn: Symbol

	column Name
		dataType: string
		lineageTag: a6ea464c-5f2b-4242-b258-f2e518d6771b
		summarizeBy: none
		sourceColumn: Name

	column Group
		dataType: string
		lineageTag: 6aa104ce-214a-43e8-9494-6519618d1318
		summarizeBy: none
		sourceColumn: Group

	column Region
		dataType: string
		lineageTag: 4f94cdac-7b4b-489f-86c8-a725a6886993
		summarizeBy: none
		sourceColumn: Region

	column Date
		dataType: dateTime
		lineageTag: 0fbea78b-49ca-4ace-82e9-67dd7cdb1dc8
		summarizeBy: none
		sourceColumn: Date

	column Close
		dataType: double
		lineageTag: 4516b0c2-6806-4080-acaa-2e6cdfe8f794
		summarizeBy: none
		sourceColumn: Close

	partition IndexPrices = m
		mode: import
		source =
				// Query name : IndexPrices        (LOAD: ON)  - 1 year of closes per index / commodity / FX; powers rebased comparison charts.
				let
				    Ok       = Table.SelectRows(StgIndices, each [Status] = "OK"),
				    WithHist = Table.AddColumn(Ok, "Hist", each [Chart][Hist], type table),
				    Keep     = Table.SelectColumns(WithHist, {"Symbol", "Name", "Group", "Region", "Hist"}),
				    Expanded = Table.ExpandTableColumn(Keep, "Hist", {"Date", "Close"}),
				    Typed    = Table.TransformColumnTypes(Expanded, {{"Symbol", type text}, {"Name", type text}, {"Group", type text}, {"Region", type text}, {"Date", type date}, {"Close", type number}})
				in
				    Typed

	annotation PBI_ResultType = Table
